definitions:
  mixin.GetDirectoriesCaseRes:
    properties:
      hasNextPages:
        example: true
        format: bool
        type: boolean
      hasPrevPages:
        example: true
        format: bool
        type: boolean
      items:
        items:
          $ref: '#/definitions/mixin.GetDirectoryCaseRes'
          format: '[]GetDirectoryCaseRes'
        type: array
      pageIndex:
        example: 1
        format: int
        type: integer
      pageSize:
        example: 10
        format: int
        type: integer
      totalCount:
        example: 50
        format: int
        type: integer
      totalPages:
        example: 5
        format: int
        type: integer
    type: object
  mixin.GetDirectoryCaseRes:
    type: object
  mixin.GetFilesCaseRes:
    type: object
  mixin.GetInfoCaseRes:
    properties:
      id:
        example: 1
        format: uint64
        type: integer
      isDirectory:
        example: true
        format: bool
        type: boolean
      name:
        example: a new dir
        format: string
        type: string
    type: object
  woosh.ProblemDetails:
    properties:
      detail:
        example: a error detail
        format: string
        type: string
      instance:
        example: /api/to/path
        format: string
        type: string
      status:
        example: 400
        format: int
        type: integer
      title:
        example: a error title
        format: string
        type: string
    type: object
info:
  contact: {}
  description: DDD-based file storage management project built with Gin.
  title: Power File Storage API
  version: "1.0"
paths:
  /api/fs/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 文件id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mixin.GetInfoCaseRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
      summary: 获取文件或目录的详细信息
      tags:
      - fs
  /api/fs/{id}/directories:
    get:
      consumes:
      - application/json
      parameters:
      - description: 目录id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mixin.GetDirectoriesCaseRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
      summary: 获取指定目录下一层级的目录列表
      tags:
      - fs
  /api/fs/{id}/files:
    get:
      consumes:
      - application/json
      parameters:
      - description: 目录id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mixin.GetFilesCaseRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/woosh.ProblemDetails'
      summary: 获取指定目录下一层级的文件列表
      tags:
      - fs
swagger: "2.0"
