definitions:
  directory.GetDirectoriesCaseRes:
    properties:
      hasNextPages:
        example: true
        format: bool
        type: boolean
      hasPrevPages:
        example: true
        format: bool
        type: boolean
      items:
        items:
          $ref: '#/definitions/directory.GetDirectoryCaseRes'
          format: '[]GetDirectoryCaseRes'
        type: array
      pageIndex:
        example: 1
        format: int
        type: integer
      pageSize:
        example: 10
        format: int
        type: integer
      totalCount:
        example: 50
        format: int
        type: integer
      totalPages:
        example: 5
        format: int
        type: integer
    type: object
  directory.GetDirectoryCaseRes:
    type: object
  directory.GetFilesCaseRes:
    type: object
  directory.GetInfoCaseRes:
    type: object
  file.GetInfoCaseRes:
    type: object
  http.ProblemDetails:
    properties:
      detail:
        example: a error detail
        format: string
        type: string
      instance:
        example: /api/to/path
        format: string
        type: string
      status:
        example: 400
        format: int
        type: integer
      title:
        example: a error title
        format: string
        type: string
    type: object
info:
  contact: {}
  description: DDD-based file storage management project built with Gin.
  title: Power File Storage API
  version: "1.0"
paths:
  /api/fs/directories/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 目录id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/directory.GetInfoCaseRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ProblemDetails'
      summary: 获取目录详细信息
      tags:
      - directories
  /api/fs/directories/{id}/directories:
    get:
      consumes:
      - application/json
      parameters:
      - description: 目录id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/directory.GetDirectoriesCaseRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ProblemDetails'
      summary: 获取指定目录下一层级的目录列表
      tags:
      - directories
  /api/fs/directories/{id}/files:
    get:
      consumes:
      - application/json
      parameters:
      - description: 目录id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/directory.GetFilesCaseRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ProblemDetails'
      summary: 获取指定目录下一层级的文件列表
      tags:
      - directories
  /api/fs/files/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 文件id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/file.GetInfoCaseRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ProblemDetails'
      summary: 获取文件详细信息
      tags:
      - files
swagger: "2.0"
