info:
  contact: {}
  description: DDD-based file storage management project built with Gin.
  title: Power File Storage API
  version: "1.0"
paths:
  /api/fs/file/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 文件id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: 获取文件详细信息
      tags:
      - files
swagger: "2.0"
